# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: username
#   password: password
#   socket: /var/run/mysqld/mysqld.sock

# development:
#   <<: *default
#   database: database-development

# test:
#   <<: *default
#   database: database_test

# production:
#   <<: *default
#   database: database_production
#   username: database_username
#   password: <%= ENV["SCHEDULED_TWEETS_DATABASE_PASSWORD"] %>
